name: Deploy site
on: [push, pull_request]
  branches: master

jobs:
  deploy:
    name: "Deploy site to production"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >> ~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            USER $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}

      - name: Checkout repo
        run: ssh deploy 'cd repeatedpleasant.games && git fetch && git reset --hard origin/master'